# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'friend-finder' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!


  # Pods for friend-finder

    # Firebase pod for Google Analytics
      pod 'Firebase/Analytics'

    pod 'Firebase'
    pod 'Firebase/Database'

    # Firebase pod for authentication with Firebase
    # using Password-Based Accounts on iOS
    pod 'Firebase/Auth'
      
    # add pods for any other desired Firebase products
    # https://firebase.google.com/docs/ios/setup#available-pods

end
